config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'

  resources :contacts, only: :create
  get 'about', to: 'contacts#new', as: 'new_contact'


  resources :profiles

  get 'breeders', to: 'profiles#index', as: 'breeders'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
	validates :comments, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  	# Redirects to breeder page after signing in 
	def after_sign_in_path_for(resource)
		profiles_path
	end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)

		if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]

      ContactMailer.contact_email(name, email, body).deliver
      
      flash[:success] = "Message sent."
			redirect_to new_contact_path
		else
			flash[:danger] = @contact.errors.full_messages.join(". ")
			redirect_to new_contact_path
		end
	end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :check_signed_in

	# Redirect to breeder page if user visits / when logged in
	def check_signed_in
	  redirect_to profiles_path if signed_in?
	end

	def index

	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!


	def new
		@profile = Profile.new
	end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to profiles_path
    else
      render action: :new
    end
  end

  # GET to /profiles/:id/edit
  def edit 
    @profile = Profile.find(params[:id])
  end

  # PATCH/PUT to /profile/:id
  def update
    # Retrieve user from database
    @profile = Profile.find(params[:id])
    # Mass assign edited profile attributes and save/update
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated!"
      # Redirect user to their profile page
      redirect_to root_path
    else
      # Otherwise, take them back to the edit action
      render action: :edit
    end
  end

  def index
  end


  private
    def profile_params
      params.require(:profile).permit(:breeder_name, :dog_breed, :phone_number, :email, :website)
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    flash.delete(:notice)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    flash.delete(:notice)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container about-contact">
  <div class="row">
    <div class="col-md-7">
    <h3 class="text-center">About</h3>
      <p>DB.DB is where you can browse and research breeders for all dog breeds. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>

    <div class="col-md-4 col-md-offset-1 contact-form">
    <h3 class="text-center">Contact Us</h3>
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %> 
      <% end %> 
      <div class="well contact-well">
        <%= form_for @contact do |f| %>
          <div class="field form-group">
            <%= f.label :name, class: 'form-label' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="field form-group">
            <%= f.label :email, class: 'form-label' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="field form-group">
            <%= f.label :comments, class: 'form-label'%>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>

          <%= f.submit 'Submit', class: 'btn btn-form' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<footer class="site-footer">
  <p><a href="https://github.com/toowan/" target="_blank">toowan</a> &copy; 2017</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>db.db</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if user_signed_in? %>
            <%= link_to breeders_path, class: "navbar-brand" do %><i class="fa fa-paw"></i> DB.DB<% end %> </p>
          <% else %>
            <%= link_to root_path, class: "navbar-brand" do %><i class="fa fa-paw"></i> DB.DB<% end %> </p>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Breeders", breeders_path %></li>
              <li><%= link_to "My Account", edit_user_registration_path %></li>
              <li><%= link_to "About", new_contact_path %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            <% else %>
              <li><%= link_to "Log In", new_user_session_path %>
              <li><%= link_to "Register", new_user_registration_path %>
              <li><%= link_to "About", new_contact_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>


    <%= yield %>




  </body>

</html>

app/views/pages/index.html.erb
<div class="container-fluid">
	<% if user_signed_in? %>
    <div class="text-center db-container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <p><%= link_to "View All Breeders", profiles_path %></p>
        </div>
      </div>
    </div>
	<% else %>
    <div class="row-fluid">
  	  <div class="home-callout text-center centering">
  			<h2 class="tagline">Find and research reputable dog breeders.</h2>
        <h3><%= link_to "Log In", new_user_session_path, class: "btn btn-lg home-button" %></h3>
  			<h3><%= link_to "Register", new_user_registration_path, class: "btn btn-lg home-button" %></h3>
  		</div>
    </div>
	<% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <div class="form-group">
    <%= f.label :breeder_name %>
    <%= f.text_field :breeder_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :dog_breed %>
    <%= f.text_field :dog_breed, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Add", class: 'btn btn-form' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center">Edit Dog Breeder Profile</h1>
		    <div class="well">
	        <%= render 'form' %>
		    </div>
		</div>
	</div>
</div>

app/views/profiles/index.html.erb
<div class="container breeder-table">
  <p class="add-breeder-link"><%= link_to "Add a Breeder", new_profile_path %></p>
  <div class="well">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>Breeder</th>
          <th>Breed</th>
          <th>Location</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Website</th>
        </tr>
      </thead>
      <tbody>
        <% Profile.all.each do |profile| %>
        <tr>
          <td><%= profile.breeder_name %></td>
          <td><%= profile.dog_breed %></td>
          <td><%= profile.location %></td>
          <td><%= mail_to profile.email, profile.email %></td>
          <td><%= profile.phone_number %></td>
          <td><%= link_to profile.website, profile.website, :target => "_blank" %></td>
        <tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<footer class="site-footer">
  <p><a href="https://github.com/toowan/" target="_blank">toowan</a> &copy; 2017</p>
</footer>

app/views/profiles/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center">Create a Dog Breeder Profile</h1>
		    <div class="well">
	        <%= render 'form' %>
		    </div>
		</div>
	</div>
</div>

<footer class="site-footer">
  <p><a href="https://github.com/toowan/" target="_blank">toowan</a> &copy; 2017</p>
</footer>